#! /bin/bash
yum update -y
hostnamectl set-hostname petclinic-dev-server #Set a Particular Host Name.
amazon-linux-extras install docker -y # install docker
systemctl start docker 
systemctl enable docker
usermod -a -G docker ec2-user # gives sudo to ec2-user
curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" \ #download the docker compose
-o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose # give execution command to docker-compose
yum install git -y #instal git
yum install java-11-amazon-corretto -y #install java-11
git clone https://github.com/clarusway/petclinic-microservices.git
cd petclinic-microservices
git fetch
git checkout dev
